---
- hosts: all

  tasks:
   - name: Install Remi repo.
     yum:
      name: "http://rpms.remirepo.net/enterprose/remi-release-7.rpm"
      state: present

   - name: Import Remi GPG key.
     rpm_key:
      key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
      state: present

   - name: Install EPEL repo.
     yum: name=epel-release state=present

   - name: Ensure firewalld is stopped (since this is for testing).
     service: name=firewalld state=stopped

   - name: Install Node.js and npm.
     yum: name=npm state=present enablerepo=epel

   - name: Install Node.js and npm.
     yum: name=npm state=present enablerepo=epel

   - name: Install Forever (to run our Node.js app)
     npm: name=forever global=yes state=present
